version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: semantic_pg
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: semantic_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: semantic_app
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  pg_data:
